// Mock data for the issue list prototype. Nothing here is wired to production code.
// The workflow mirrors the example `workflow.toml` in docs/product/prd.md.

window.PUNCHLIST_MOCK = (function () {
  const statuses = [
    { id: "backlog", label: "Backlog", kind: "backlog", next: { by: "person", gates: [] } },
    { id: "todo", label: "Todo", kind: "unstarted", next: { by: "person", gates: [] } },
    { id: "start", label: "Start", kind: "unstarted", next: { by: "runner", gates: [] } },
    {
      id: "in_progress",
      label: "In Progress",
      kind: "started",
      dispatch: "claude-code",
      next: { by: "agent", gates: ["pr_open", "pr_ready", "pr_names_issue"] },
    },
    {
      id: "agent_review",
      label: "Agent Review",
      kind: "started",
      dispatch: "codex",
      next: { by: "agent", gates: ["ci_green", "mergeable", "no_open_threads", "proof_attached"] },
    },
    {
      id: "human_review",
      label: "Human Review",
      kind: "started",
      lock: ["agent", "runner"],
      next: { by: "person", gates: [] },
    },
    { id: "merging", label: "Merging", kind: "started", next: { by: "event", event: "pr_merged", gates: [] } },
    { id: "done", label: "Done", kind: "completed", next: null },
    { id: "canceled", label: "Canceled", kind: "canceled", next: null },
  ];

  const gateLabels = {
    pr_open: "PR open",
    pr_ready: "PR ready",
    pr_names_issue: "PR names issue",
    ci_green: "CI green",
    mergeable: "Mergeable",
    no_open_threads: "No open threads",
    proof_attached: "Proof attached",
  };

  const actors = {
    gannon: { id: "gannon", type: "person", name: "Gannon Hall", initials: "GH" },
    priya: { id: "priya", type: "person", name: "Priya Natarajan", initials: "PN" },
    claude: { id: "claude", type: "agent", kind: "claude-code", name: "Claude Code", initials: "CC" },
    codex: { id: "codex", type: "agent", kind: "codex", name: "Codex", initials: "CX" },
    opencode: { id: "opencode", type: "agent", kind: "opencode", name: "OpenCode", initials: "OC" },
  };

  // run: { state: queued | running | failed | idle, agent?, detail?, since? }
  // pr:  { number, state: draft | open | merged | closed, checks: passing | failing | pending | none } or null
  // gates: results recorded by the server for the next transition's gates.
  const issues = [
    // Backlog
    {
      id: "PL-131",
      title: "Inbox for people: issues waiting on a person, refused transitions, failed runs",
      status: "backlog",
      assignee: null,
      labels: ["feature"],
      run: { state: "idle" },
      pr: null,
      gates: {},
      updated: "2d",
    },
    {
      id: "PL-129",
      title: "Search across issues and comments",
      status: "backlog",
      assignee: "priya",
      labels: ["feature"],
      run: { state: "idle" },
      pr: null,
      gates: {},
      updated: "3d",
    },
    {
      id: "PL-127",
      title: "Convert a Symphony WORKFLOW.md into workflow.toml and prompts",
      status: "backlog",
      assignee: null,
      labels: ["feature", "import"],
      run: { state: "idle" },
      pr: null,
      gates: {},
      updated: "5d",
    },
    // Todo
    {
      id: "PL-124",
      title: "Runner: recover held leases after a restart without running an issue twice",
      status: "todo",
      assignee: "claude",
      labels: ["runner"],
      run: { state: "idle" },
      pr: null,
      gates: {},
      updated: "1d",
    },
    {
      id: "PL-122",
      title: "Publish the JSON Schema for workflow.toml",
      status: "todo",
      assignee: "gannon",
      labels: ["chore"],
      run: { state: "idle" },
      pr: null,
      gates: {},
      updated: "1d",
    },
    // Start
    {
      id: "PL-120",
      title: "Transition API returns the failing gate and its reason",
      status: "start",
      assignee: "codex",
      labels: ["server"],
      run: { state: "queued", agent: "codex", detail: "waiting for a runner slot (5 of 5 busy)" },
      pr: null,
      gates: {},
      updated: "12m",
    },
    {
      id: "PL-119",
      title: "GitHub App: link a pull request by branch name",
      status: "start",
      assignee: "opencode",
      labels: ["github"],
      run: { state: "queued", agent: "opencode", detail: "claimed by sartre, creating worktree" },
      pr: null,
      gates: {},
      updated: "4m",
    },
    // In Progress
    {
      id: "PL-118",
      title: "Parse and validate workflow.toml into typed data",
      status: "in_progress",
      assignee: "claude",
      labels: ["core"],
      run: { state: "running", agent: "claude", detail: "cargo test punchlist-core", since: "14m" },
      pr: { number: 212, state: "draft", checks: "pending" },
      gates: { pr_open: true, pr_ready: false, pr_names_issue: true },
      updated: "1m",
    },
    {
      id: "PL-117",
      title: "Append-only event log and per-issue timeline",
      status: "in_progress",
      assignee: "opencode",
      labels: ["server"],
      run: { state: "running", agent: "opencode", detail: "writing migration 0004_events", since: "32m" },
      pr: null,
      gates: { pr_open: false, pr_names_issue: false, pr_ready: false },
      updated: "3m",
    },
    {
      id: "PL-116",
      title: "Separate identities and API tokens for people and agents",
      status: "in_progress",
      assignee: "codex",
      labels: ["server", "auth"],
      run: { state: "failed", agent: "codex", detail: "exit 1 after 9m: sqlx migrate failed", since: "41m" },
      pr: { number: 209, state: "draft", checks: "failing" },
      gates: { pr_open: true, pr_ready: false, pr_names_issue: true },
      updated: "41m",
    },
    {
      id: "PL-115",
      title: "Issue page: runs with logs, duration and cost",
      status: "in_progress",
      assignee: "claude",
      labels: ["web"],
      run: { state: "queued", agent: "claude", detail: "retry 2 of 3 in 6m" },
      pr: { number: 207, state: "draft", checks: "none" },
      gates: { pr_open: true, pr_ready: false, pr_names_issue: false },
      updated: "9m",
    },
    // Agent Review
    {
      id: "PL-114",
      title: "Gates: ci_green, mergeable, no_open_threads, proof_attached",
      status: "agent_review",
      assignee: "codex",
      labels: ["core"],
      run: { state: "running", agent: "codex", detail: "answering 2 review threads", since: "6m" },
      pr: { number: 204, state: "open", checks: "passing" },
      gates: { ci_green: true, mergeable: true, no_open_threads: false, proof_attached: true },
      updated: "2m",
    },
    {
      id: "PL-113",
      title: "Runner heartbeat and lease renewal",
      status: "agent_review",
      assignee: "claude",
      labels: ["runner"],
      run: { state: "failed", agent: "claude", detail: "context limit reached", since: "2h" },
      pr: { number: 201, state: "open", checks: "failing" },
      gates: { ci_green: false, mergeable: true, no_open_threads: false, proof_attached: false },
      updated: "2h",
    },
    {
      id: "PL-112",
      title: "MCP server: read an issue, comment, attach proof",
      status: "agent_review",
      assignee: "opencode",
      labels: ["mcp"],
      run: { state: "idle", agent: "opencode" },
      pr: { number: 198, state: "open", checks: "passing" },
      gates: { ci_green: true, mergeable: true, no_open_threads: true, proof_attached: false },
      updated: "35m",
    },
    // Human Review
    {
      id: "PL-111",
      title: "Linear import: issues, statuses, projects and labels",
      status: "human_review",
      assignee: "gannon",
      labels: ["import"],
      run: { state: "idle" },
      pr: { number: 195, state: "open", checks: "passing" },
      gates: {},
      updated: "3h",
    },
    {
      id: "PL-110",
      title: "Docker Compose self-host: web, worker, Postgres",
      status: "human_review",
      assignee: "priya",
      labels: ["chore"],
      run: { state: "idle" },
      pr: { number: 193, state: "open", checks: "passing" },
      gates: {},
      updated: "1d",
    },
    // Merging
    {
      id: "PL-109",
      title: "Upload proof through MCP, CLI and the web app",
      status: "merging",
      assignee: "gannon",
      labels: ["feature"],
      run: { state: "idle" },
      pr: { number: 190, state: "open", checks: "passing" },
      gates: {},
      updated: "20m",
    },
    // Done
    {
      id: "PL-108",
      title: "Issues: create and edit with a Markdown body",
      status: "done",
      assignee: "claude",
      labels: ["feature"],
      run: { state: "idle", agent: "claude" },
      pr: { number: 186, state: "merged", checks: "passing" },
      gates: {},
      updated: "2d",
    },
    {
      id: "PL-105",
      title: "Cargo workspace with punchlist-core, server, runner and pl",
      status: "done",
      assignee: "gannon",
      labels: ["chore"],
      run: { state: "idle" },
      pr: { number: 180, state: "merged", checks: "passing" },
      gates: {},
      updated: "4d",
    },
    // Canceled
    {
      id: "PL-103",
      title: "Native GPUI client",
      status: "canceled",
      assignee: null,
      labels: [],
      run: { state: "idle" },
      pr: { number: 171, state: "closed", checks: "none" },
      gates: {},
      updated: "6d",
    },
  ];

  return { statuses, gateLabels, actors, issues };
})();
